// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OmsUIClient is the client API for OmsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OmsUIClient interface {
	// ListEngineSpecs returns a list of Order Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (OmsUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type omsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewOmsUIClient(cc grpc.ClientConnInterface) OmsUIClient {
	return &omsUIClient{cc}
}

func (c *omsUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (OmsUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &OmsUI_ServiceDesc.Streams[0], "/v1.OmsUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &omsUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OmsUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type omsUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *omsUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *omsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.OmsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OmsUIServer is the server API for OmsUI service.
// All implementations must embed UnimplementedOmsUIServer
// for forward compatibility
type OmsUIServer interface {
	// ListEngineSpecs returns a list of Order Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, OmsUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedOmsUIServer()
}

// UnimplementedOmsUIServer must be embedded to have forward compatible implementations.
type UnimplementedOmsUIServer struct {
}

func (UnimplementedOmsUIServer) ListEngineSpecs(*ListEngineSpecsRequest, OmsUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedOmsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedOmsUIServer) mustEmbedUnimplementedOmsUIServer() {}

// UnsafeOmsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OmsUIServer will
// result in compilation errors.
type UnsafeOmsUIServer interface {
	mustEmbedUnimplementedOmsUIServer()
}

func RegisterOmsUIServer(s grpc.ServiceRegistrar, srv OmsUIServer) {
	s.RegisterService(&OmsUI_ServiceDesc, srv)
}

func _OmsUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OmsUIServer).ListEngineSpecs(m, &omsUIListEngineSpecsServer{stream})
}

type OmsUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type omsUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *omsUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _OmsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.OmsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OmsUI_ServiceDesc is the grpc.ServiceDesc for OmsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OmsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.OmsUI",
	HandlerType: (*OmsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _OmsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _OmsUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "oms-ui.proto",
}
